server:
  port: 8181

spring:
  security:
    oauth2:
      resource:
        jwk:
          key-set-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs
          
logging:
  level: 
    org.springframework: debug